
services:
  # Backend (API)
  backend:
    build: ./backend
    platform: linux/arm64/v8
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/mydatabase
    restart: unless-stopped

  # Frontend (Dashboard)
  frontend:
    build: ./frontend
    platform: linux/arm64/v8
    ports:
      - "8080:80"
    restart: unless-stopped

  # DB
  db:
    image: postgres:14-alpine
    platform: linux/arm64/v8
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d mydatabase" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
